### ISSUE TITLE
MBTI 유형별 설명, 퍼스널컬러 관리 페이지의 필요성

### ISSUE THREAD

**Issue by rebi13** [MBTI-Inside/client#22]
MBTI는 총 16가지 유형이 있으며 이는 불변하는 상수값으로 생각할 수 있다.

따라서 데이터를 한 번 말아넣으면 추후 수정할 일은 오타의 이슈가 아닌 이상 크게 없을 것.

관리용 페이지를 과연 만들어야 할 지?

(기존 Are You T에서는 api만 만들어서 postman으로 CRUD 관리했었음)

테스트 결과 페이지에서 보여지는 데이터들
- 특정 MBTI의 설명
- 특정 MBTI의 해시태그 (4개)
- 특정 MBTI와 잘 맞는 유형 및 설명
- 특정 MBTI와 안 맞는 유형 및 설명

@MCprotein 의견 부탁드립니다.

**Comment by MCprotein** [comment]
상수취급이면 굳이 만들지 않아도 될거같습니다
추후 수정할일이 많아진다면 다시 고려해보는건 어떠신가요?

**Comment by MCprotein** [comment]
그리고 말씀하신 데이터 버전관리 할거아니면 CRUD 도 안만들고 DB 직접 수정해도 괜찮을거같습니다
필요하다면 일단 우선순위 높은 기능 먼저 하고 나중에 해도 괜찮을거같은데 이부분은 어떻게 생각하시나요?

**Comment by rebi13** [comment]
좋은 의견 감사합니다.
추후 필요하면 그 때 다시 생각해 보도록 하시죠!
확인 후 이슈 닫아주시면 감사드리겠습니다 😄
